waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12343207016
      customize:
        - type: rubbish
          alias: General Waste
          icon: mdi:delete
        - type: recycle
          alias: Recycling
          icon: mdi:recycle

sensor:
  - platform: waste_collection_schedule
    name: waste collection
    details_format: "generic"
    value_template: '{{value.types|join(" + ")}} in {{value.daysTo}} days'
  - platform: waste_collection_schedule
    name: waste collection recycling
    details_format: "upcoming"
    types:
      - recycle
    value_template: "{{ value.daysTo }}"
  - platform: waste_collection_schedule
    name: waste collection rubbish
    details_format: "upcoming"
    types:
      - rubbish
    value_template: "{{ value.daysTo }}"
