- id: '1650151312876'
  alias: Pantry Motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.pantry_motion
      lightsensor_entity: sensor.theben_brigthness_west
      illuminace_level: 200
      light_target:
        entity_id: light.pantry_downlights
      scene_morning: scene.pantry_78
      scene_day: scene.pantry_78
      scene_evening: scene.pantry_78
      scene_night: scene.pantry_78
      no_motion_wait: 20
- id: '1650153536036'
  alias: Storage light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.storage_motion
      light_target:
        entity_id: light.storage_downlights
      no_motion_wait: 15
- id: '1650170604508'
  alias: Garage motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.garage_motion
      lightsensor_entity: sensor.theben_brigthness_max
      light_target:
        entity_id: light.garage_battons
      scene_morning: scene.garage_100
      scene_day: scene.garage_100
      scene_evening: scene.garage_100
      scene_night: scene.garage_100
- id: '1650173341970'
  alias: Main Bath motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.main_bathroom_motion
      lightsensor_entity: sensor.theben_brigthness_max
      light_target:
        entity_id: light.main_bath_vanity
      scene_night: scene.vanity_night
      time_scene_evening: '18:00:00'
      time_scene_night: '22:00:00'
      time_scene_morning: 06:00:00
      time_scene_day: '10:00:00'
      scene_morning: scene.vanity_sunrise
      scene_evening: scene.vanity_sunset
      no_motion_wait: 30
- id: '1650243347012'
  alias: Entry motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.entry_motion
      lightsensor_entity: sensor.theben_brigthness_max
      light_target:
        entity_id:
        - light.entry_downlight
      illuminace_level: 300
      scene_morning: scene.entry_sunrise
      time_scene_morning: 05:00:00
      time_scene_day: 08:00:00
      time_scene_evening: '17:00:00'
      scene_evening: scene.entry_sunset
      scene_night: scene.entry_night
      time_scene_night: '22:00:00'
      no_motion_wait: 30
- id: 31f60e49-edfd-469a-a271-365f76b4a066
  alias: Entry Back motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.entry_hallway_motion
      lightsensor_entity: sensor.theben_brigthness_max
      light_target:
        entity_id:
        - light.entry_back_downlight
      illuminace_level: 300
      scene_morning: scene.entry_back_sunrise
      time_scene_morning: 05:00:00
      time_scene_day: 08:00:00
      time_scene_evening: '17:00:00'
      scene_evening: scene.entry_back_sunset
      scene_night: scene.entry_back_night
      time_scene_night: '22:00:00'
      no_motion_wait: 15
- id: '1650442686802'
  alias: Utility motion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.utility_motion
      light_target:
        entity_id: light.utility_downlights
      no_motion_wait: 30
- id: '1650444502931'
  alias: Staircase Motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.stairs_motion
      lightsensor_entity: sensor.theben_brigthness_max
      light_target:
        entity_id: light.stairs_handrail
      illuminace_level: 100
      no_motion_wait: 30
      scene_morning: scene.staircase_sunrise
      time_scene_morning: 06:00:00
      scene_evening: scene.staircase_sunset
      time_scene_evening: '18:00:00'
      scene_night: scene.staircase_night
      time_scene_night: '22:00:00'
- id: '1650532509592'
  alias: Laundry motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.laundry_motion
      lightsensor_entity: sensor.laundry_brightness
      illuminace_level: 600
      light_target:
        entity_id: light.laundry_downlights
      scene_morning: scene.laundry_sunrise
      time_scene_morning: 05:00:00
      scene_day: scene.laundry_day
      time_scene_day: 08:00:00
      scene_evening: scene.laundry_sunset
      time_scene_evening: '17:00:00'
      scene_night: scene.laundry_night
      time_scene_night: '22:00:00'
      no_motion_wait: 60
- id: '1650532855924'
  alias: Guest Bathroom motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.guest_bathroom_motion
      lightsensor_entity: sensor.guest_bathroom
      light_target:
        entity_id: light.guest_bath_downlights
      scene_morning: scene.guest_bathroom_sunrise
      time_scene_morning: 05:00:00
      scene_day: scene.guest_bathroom_day
      time_scene_day: 08:00:00
      scene_evening: scene.guest_bathroom_sunset
      time_scene_evening: '18:00:00'
      scene_night: scene.guest_bathroom_night
      time_scene_night: '22:00:00'
- id: f9a69b4a-fa71-489a-8d2c-3e911104622c
  alias: Wardrobe motion
  description: ''
  use_blueprint:
    path: dirkk1980/motion_controlled_scenes_enhanced.yaml
    input:
      motion_entity: binary_sensor.wardrobe_motion
      lightsensor_entity: sensor.theben_brigthness_max
      illuminace_level: 200
      light_target:
        entity_id: light.wardrobe_downlights
      scene_morning: scene.wardrobe_sunrise
      time_scene_morning: 05:00:00
      scene_evening: scene.wardrobe_sunset
      time_scene_evening: '18:00:00'
      scene_night: scene.wardrobe_night
      time_scene_night: '23:00:00'
      no_motion_wait: 30
- id: '1652257933005'
  alias: Update home.mohni.info IP
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.myip
  condition: []
  action:
  - service: shell_command.update_ddns
    data: {}
  mode: single
- id: '1653559835118'
  alias: Turn off Guest Bathroom HTR
  description: ''
  use_blueprint:
    path: Talvish/timed_turn_off.yaml
    input:
      target_switch: switch.guest_bathroom_htr
      time_period:
        hours: 1
        minutes: 0
        seconds: 0
- id: '1653559873676'
  alias: Turn off Main Bathroom HTR
  description: ''
  use_blueprint:
    path: Talvish/timed_turn_off.yaml
    input:
      target_switch: switch.main_bathroom_htr
      time_period:
        hours: 1
        minutes: 0
        seconds: 0
- id: '1654684563814'
  alias: Sleep Mode activated
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.knx_sleep_mode
  condition: []
  action:
  - if:
    - condition: state
      entity_id: switch.knx_sleep_mode
      state: 'on'
    then:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id:
        - input_boolean.keypad_mode_house
        - input_boolean.keypad_mode_master
        - input_boolean.motion_sensor_main_bathroom
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.motion_sensor_main_bathroom_disabled
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.grp_house
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id:
        - input_boolean.keypad_mode_house
        - input_boolean.keypad_mode_master
        - input_boolean.motion_sensor_main_bathroom
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.motion_sensor_main_bathroom_disabled
  mode: single
- id: '1654765793972'
  alias: Turn on House Keypads
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.keypad_mode_house
      - input_boolean.motion_sensor_main_bathroom
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.motion_sensor_main_bathroom_disabled
  mode: single
- id: '1657440634725'
  alias: Turn off Garage Fan
  description: ''
  use_blueprint:
    path: Talvish/timed_turn_off.yaml
    input:
      target_switch: switch.garage_ventilation
      time_period:
        hours: 1
        minutes: 0
        seconds: 0
- id: '1659243009780'
  alias: Shut Everything Down when arm away
  description: ''
  trigger:
  - platform: template
    value_template: '{{is_state_attr(''alarm_control_panel_away'',''disarmed'', False)}}'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.grp_house
  mode: single
