- id: '1652257933005'
  alias: Update home.mohni.info IP
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.myip
  condition: []
  action:
  - service: shell_command.update_ddns
    data: {}
  mode: single
- id: '1653559835118'
  alias: Turn off Guest Bathroom HTR
  description: ''
  use_blueprint:
    path: Talvish/timed_turn_off.yaml
    input:
      target_switch: switch.guest_bathroom_htr
      time_period:
        hours: 1
        minutes: 0
        seconds: 0
- id: '1653559873676'
  alias: Turn off Main Bathroom HTR
  description: ''
  use_blueprint:
    path: Talvish/timed_turn_off.yaml
    input:
      target_switch: switch.main_bathroom_htr
      time_period:
        hours: 1
        minutes: 0
        seconds: 0
- id: '1654684563814'
  alias: Sleep Mode activated
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.knx_sleep_mode
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - switch.knx_sleep_mode
    from: 'on'
    to: 'off'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: switch.knx_sleep_mode
      state: 'on'
    then:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id:
        - input_boolean.keypad_mode_house
        - input_boolean.keypad_mode_master
        - input_boolean.motion_sensor_main_bathroom
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.motion_sensor_main_bathroom_disabled
    - service: light.turn_off
      data: {}
      target:
        entity_id:
        - light.house_excl_guest_zone
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id:
        - input_boolean.keypad_mode_house
        - input_boolean.keypad_mode_master
        - input_boolean.motion_sensor_main_bathroom
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.motion_sensor_main_bathroom_disabled
  - if:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: switch.knx_sleep_mode
        state: 'on'
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.knx_guest_sleep_mode
  - if:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: switch.knx_sleep_mode
        state: 'off'
    then:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.knx_guest_sleep_mode
  mode: single
- id: '1654765793972'
  alias: Turn on House Keypads
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
      - input_boolean.keypad_mode_house
      - input_boolean.motion_sensor_main_bathroom
      - input_boolean.motion_sensor_main_bathroom_disabled
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.keypad_mode_house
      - input_boolean.motion_sensor_main_bathroom
  mode: single
- id: '1657440634725'
  alias: Turn off Garage Fan
  description: ''
  use_blueprint:
    path: Talvish/timed_turn_off.yaml
    input:
      target_switch: switch.garage_ventilation
      time_period:
        hours: 1
        minutes: 0
        seconds: 0
- id: '1659243009780'
  alias: Alarm away armed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.away
    attribute: armed
    from: false
    to: true
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.grp_house
  - service: notify.dan_signal
    data:
      message: House has been armed
  mode: single
- id: '1659516286542'
  alias: 'Bridge: Sliding gate'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.sliding_gate
  condition: []
  action:
  - if:
    - condition: state
      entity_id: switch.sliding_gate
      state: 'on'
    then:
    - service: switch.toggle
      data: {}
      target:
        entity_id: switch.crow_output_gate
  mode: single
- id: '1659517931531'
  alias: 'Bridge: Garage door'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.garage_door
  condition: []
  action:
  - if:
    - condition: state
      entity_id: switch.garage_door
      state: 'on'
    then:
    - service: switch.toggle
      data: {}
      target:
        entity_id: switch.crow_output_garage_door
  mode: single
- id: '1661053242251'
  alias: Enable Boost mode
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.guest_bathroom_humidity
    above: '90'
  - platform: numeric_state
    entity_id: sensor.main_bathroom_humidity
    above: '90'
  - platform: numeric_state
    entity_id: sensor.laundry_humidity
    above: '90'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.zehnder_boost
  mode: single
- id: '1661328084704'
  alias: KNX Switch Security
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.security_south_east
  condition: []
  action:
  - if:
    - condition: state
      entity_id: switch.security_south_east
      state: 'on'
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.security_south_east
    else:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.security_south_east
  mode: single
- id: '1672642198753'
  alias: Sleep Mode (Guest) activated
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.knx_guest_sleep_mode
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - switch.knx_guest_sleep_mode
    from: 'on'
    to: 'off'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: switch.knx_guest_sleep_mode
      state: 'on'
    then:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id:
        - input_boolean.keypad_mode_guest
    - service: light.turn_off
      data: {}
      target:
        entity_id:
        - light.guest_zone
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id:
        - input_boolean.keypad_mode_guest
  mode: single
- id: '1673061477362'
  alias: 'Set Turn On Living Pendant Brightness '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.living_pendant
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 90
    target:
      entity_id: light.living_pendant
  mode: single
- id: '1673249567666'
  alias: Set Turn On Master Downlights Brightness
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.master_downlights
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 70
    target:
      entity_id: light.master_downlights
  mode: single
- id: '1673333887007'
  alias: Test Signal notification
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.dan_signal
    data:
      message: Signal notification test
      title: Test
  mode: single
- id: '1673334623130'
  alias: KLF reboot on hass shutdown
  description: Velux KLF200 Gateway
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: velux.reboot_gateway
    data: {}
  mode: single
- id: '1673500227074'
  alias: Alarm away disarmed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.away
    attribute: armed
    from: true
    to: false
  condition: []
  action:
  - service: notify.dan_signal
    data:
      message: House has been disarmed
  mode: single
- id: '1673898775186'
  alias: Re-trigger brightness watcher
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.outdoor_brigthness_gt_100
      - input_boolean.outdoor_brigthness_gt_200
      - input_boolean.outdoor_brigthness_gt_300
      - input_boolean.outdoor_brigthness_gt_600
  - service: automation.trigger
    data: {}
    target:
      entity_id: automation.outdoor_brigthness_watcher
  mode: single
- id: '1673927543705'
  alias: Alarm triggered notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.away
    attribute: alarm
    to: true
  condition: []
  action:
  - service: notify.dan_signal
    data:
      message: Alarm has been triggered
  mode: single
- id: '1673928028407'
  alias: Home Power Supply
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.crow_alarm_system
    attribute: mains
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state != ''unknown'' }}'
  action:
  - service: notify.dan_signal
    data_template:
      message: '{% if is_state(''trigger.to_state.state'',''True'') %}  Power Back
        On...  {% else %} Power Cut!!! {% endif %}

        '
  mode: single
- id: '1674855813710'
  alias: Turn Off Security lights during day
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.security_south_east
    - light.security_north_east
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.brightness_sec_back_se
    state: '0.0'
  - condition: state
    entity_id: sensor.brightness_sec_back_ne
    state: '0.0'
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.security_north_east
      - light.security_south_east
  mode: single
- id: '1679385783744'
  alias: Entry Door left open notification
  description: ''
  trigger:
  - type: problem
    platform: device
    device_id: b977484604bd37f9e3f74c7804b75550
    entity_id: binary_sensor.door_window_sensor_3ea5_door_left_open
    domain: binary_sensor
  condition: []
  action:
  - service: notify.dan_signal
    data:
      message: Entry Door left open
  mode: single
- id: '1683708517965'
  alias: Entry Door left open resolved notification
  description: ''
  trigger:
  - type: no_problem
    platform: device
    device_id: b977484604bd37f9e3f74c7804b75550
    entity_id: binary_sensor.door_window_sensor_3ea5_door_left_open
    domain: binary_sensor
  condition: []
  action:
  - service: notify.dan_signal
    data:
      message: Entry Door closed
  mode: single
- id: '1685842769395'
  alias: 'Bridge: Downstairs Light '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.downstairs_light
    from: 'on'
    to: 'off'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.grp_downstairs
      state: 'on'
    then:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.grp_downstairs
  mode: single
- id: '1685847758767'
  alias: 'Bridge: Upstairs light'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.upstairs_light_2
    from: 'on'
    to: 'off'
  - platform: state
    entity_id:
    - switch.upstairs_light
    from: 'on'
    to: 'off'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.grp_upstairs
      state: 'on'
    then:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.grp_upstairs
  mode: single
- id: '1690361756579'
  alias: AlphaESS Enable Grid Charging Battery
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
  - platform: time
    at: '16:00:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.al2002118050331_state_of_charge
    below: input_number.grid_charging_threshold
    alias: Confirm AL2002118050331_State of Charge is below Grid Charging Threshold
  action:
  - service: alphaess.setbatterycharge
    data:
      enabled: true
      cp1start: 03:00
      cp1end: 05:00
      cp2start: '16:00'
      cp2end: '17:00'
      chargestopsoc: 80
      serial: AL2002118050331
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.al2002118050331_grid_charging_battery
  mode: single
- id: '1690364695644'
  alias: AlphaESS Disable Grid Charging Battery
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.al2002118050331_state_of_charge
    above: input_number.grid_charging_threshold
    alias: When AL2002118050331_State of Charge is above Grid Charging Threshold
  condition:
  - condition: state
    entity_id: input_boolean.al2002118050331_grid_charging_battery
    state: 'on'
  action:
  - service: alphaess.setbatterycharge
    data:
      enabled: false
      cp1start: 03:00
      cp1end: 04:00
      cp2start: '16:00'
      cp2end: '17:00'
      chargestopsoc: 50
      serial: AL2002118050331
    alias: 'Call a service ''Alpha ESS: Set Battery Charge'' off'
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.al2002118050331_grid_charging_battery
  mode: single
- id: '1692481651406'
  alias: Outdoor brigthness watcher UI
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.st_00127484_illuminance
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.brightness_sec_back_se
        below: '100'
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.outdoor_brigthness_gt_100
          - input_boolean.outdoor_brigthness_gt_200
          - input_boolean.outdoor_brigthness_gt_300
          - input_boolean.outdoor_brigthness_gt_600
    - conditions:
      - condition: numeric_state
        entity_id: sensor.brightness_sec_back_se
        above: '100'
        below: '200'
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
          - input_boolean.outdoor_brigthness_gt_100
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.outdoor_brigthness_gt_200
          - input_boolean.outdoor_brigthness_gt_300
          - input_boolean.outdoor_brigthness_gt_600
    - conditions:
      - condition: numeric_state
        entity_id: sensor.brightness_sec_back_se
        above: '200'
        below: '300'
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
          - input_boolean.outdoor_brigthness_gt_100
          - input_boolean.outdoor_brigthness_gt_200
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.outdoor_brigthness_gt_300
          - input_boolean.outdoor_brigthness_gt_600
    - conditions:
      - condition: numeric_state
        entity_id: sensor.brightness_sec_back_se
        above: '300'
        below: '600'
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
          - input_boolean.outdoor_brigthness_gt_100
          - input_boolean.outdoor_brigthness_gt_200
          - input_boolean.outdoor_brigthness_gt_300
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.outdoor_brigthness_gt_600
    - conditions:
      - condition: numeric_state
        entity_id: sensor.brightness_sec_back_se
        above: '600'
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
          - input_boolean.outdoor_brigthness_gt_100
          - input_boolean.outdoor_brigthness_gt_200
          - input_boolean.outdoor_brigthness_gt_300
          - input_boolean.outdoor_brigthness_gt_600
    default: []
  mode: single
