binary_sensor:
  - name: weatherflow_forecast_precip_total
    unique_id: "1a7c8460-c399-4bd4-988f-c26f0a41ada7"
    state: >
      {{ (state_attr('weather.weatherflow_hourly_based_forecast','forecast').0.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').1.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').2.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').3.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').4.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').5.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').6.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').7.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').8.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').9.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').10.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').11.precipitation | float(0) +
          state_attr('weather.weatherflow_hourly_based_forecast','forecast').12.precipitation | float(0) ) > 0 }}
