---
id: 'ba76da20-6d9c-43df-bd5b-71b50eb9c8ef'
alias: Outdoor brigthness watcher
description: ''
trigger:
- platform: state
  entity_id:
  - sensor.theben_brigthness_max
condition: []
action:
- choose:
  - conditions:
    - condition: numeric_state
      entity_id: sensor.theben_brigthness_max
      below: '100'
    sequence:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id:
        - input_boolean.outdoor_brigthness_gt_100
        - input_boolean.outdoor_brigthness_gt_200
        - input_boolean.outdoor_brigthness_gt_300
        - input_boolean.outdoor_brigthness_gt_600
  - conditions:
    - condition: numeric_state
      entity_id: sensor.theben_brigthness_max
      above: '100'
      below: '200'
    sequence:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id:
        - input_boolean.outdoor_brigthness_gt_100
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id:
        - input_boolean.outdoor_brigthness_gt_200
        - input_boolean.outdoor_brigthness_gt_300
        - input_boolean.outdoor_brigthness_gt_600
  - conditions:
    - condition: numeric_state
      entity_id: sensor.theben_brigthness_max
      above: '200'
      below: '300'
    sequence:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id:
        - input_boolean.outdoor_brigthness_gt_100
        - input_boolean.outdoor_brigthness_gt_200
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id:
        - input_boolean.outdoor_brigthness_gt_300
        - input_boolean.outdoor_brigthness_gt_600
  - conditions:
    - condition: numeric_state
      entity_id: sensor.theben_brigthness_max
      above: '300'
      below: '600'
    sequence:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id:
        - input_boolean.outdoor_brigthness_gt_100
        - input_boolean.outdoor_brigthness_gt_200
        - input_boolean.outdoor_brigthness_gt_300
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id:
        - input_boolean.outdoor_brigthness_gt_600
  - conditions:
    - condition: numeric_state
      entity_id: sensor.theben_brigthness_max
      above: '600'
    sequence:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id:
        - input_boolean.outdoor_brigthness_gt_100
        - input_boolean.outdoor_brigthness_gt_200
        - input_boolean.outdoor_brigthness_gt_300
        - input_boolean.outdoor_brigthness_gt_600
  default: []
mode: single