- platform: generic
  name: Garage
  username: !secret hikvision_username
  password: !secret hikvision_password
  still_image_url: http://username:password@192.168.17.205/ISAPI/Streaming/channels/101/picture
  stream_source: rtsp://username:password@192.168.17.205:554/Streaming/channels/101
- platform: generic
  name: Entry
  username: !secret hikvision_username
  password: !secret hikvision_password
  still_image_url: http://username:password@192.168.17.205/ISAPI/Streaming/channels/201/picture
  stream_source: rtsp://username:password@192.168.17.205:554/Streaming/channels/201
- platform: generic
  name: Deck
  username: !secret hikvision_username
  password: !secret hikvision_password
  still_image_url: http://username:password@192.168.17.205/ISAPI/Streaming/channels/301/picture
  stream_source: rtsp://username:password@192.168.17.205:554/Streaming/channels/301
- platform: generic
  name: Garden
  username: !secret hikvision_username
  password: !secret hikvision_password
  still_image_url: http://username:password@192.168.17.205/ISAPI/Streaming/channels/401/picture
  stream_source: rtsp://username:password@192.168.17.205:554/Streaming/channels/401
