substitutions:
  name: atom-bluetooth-proxy-d4dcb4
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: pjBnteU2dLAZBs1C+46auGl4jRvty6DK7oUoDl0Ci0A=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
