substitutions:
  name: atom-bluetooth-proxy-d4dcb4
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

logger:
#  level: VERY_VERBOSE
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
